// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUSoAE61sSw3pwvmopbolgghkaZwTtC2o',
    appId: '1:576902459702:web:e5aa59788b80bfad2f0397',
    messagingSenderId: '576902459702',
    projectId: 'chat-app-3cf3d',
    authDomain: 'chat-app-3cf3d.firebaseapp.com',
    storageBucket: 'chat-app-3cf3d.appspot.com',
    measurementId: 'G-5QMDZMGMGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCXWE1KsCeehIP3SA79keQjWpiBvVUx5Y',
    appId: '1:576902459702:android:4aa8e6c7457b9aa22f0397',
    messagingSenderId: '576902459702',
    projectId: 'chat-app-3cf3d',
    storageBucket: 'chat-app-3cf3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBICnrD8R0TsjNPOTZzo7U7wwruGLPsyOY',
    appId: '1:576902459702:ios:dda6cb715f8c00242f0397',
    messagingSenderId: '576902459702',
    projectId: 'chat-app-3cf3d',
    storageBucket: 'chat-app-3cf3d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBICnrD8R0TsjNPOTZzo7U7wwruGLPsyOY',
    appId: '1:576902459702:ios:dda6cb715f8c00242f0397',
    messagingSenderId: '576902459702',
    projectId: 'chat-app-3cf3d',
    storageBucket: 'chat-app-3cf3d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUSoAE61sSw3pwvmopbolgghkaZwTtC2o',
    appId: '1:576902459702:web:0043186fd7d498bf2f0397',
    messagingSenderId: '576902459702',
    projectId: 'chat-app-3cf3d',
    authDomain: 'chat-app-3cf3d.firebaseapp.com',
    storageBucket: 'chat-app-3cf3d.appspot.com',
    measurementId: 'G-FFDQ1VFHYL',
  );

}